version: "3.7"
services:
  db:
    image: postgres:latest
    ports:
      - target: 5432
        published: 5000-6000
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: data
        target: /docker-entrypoint-initdb.d/
    networks: 
      - golang_postgreSQL
  web_service:
    build: 
      context: .
      labels:
        "golang.go.goal=Run the main program an access to the database viewnext to get data"
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    networks: 
      - golang_postgreSQL
volumes:
  data: db/