version: "3.7"
services:
  db:
    image: postgres:latest
    expose: 
      - 5432
    ports:
      - target: 5432
        published: "5000-6000"
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: data
        target: /docker-entrypoint-initdb.d/
      - type: volume
        source: passwd
        target: /docker-entrypoint-initdb.d/secrets
    networks: 
      - golang_postgreSQL
    env:
      - POSTGRES_DB viewnext
      - POSTGRES_USER root
      - POSTGRES_PASSWORD_FILE=/docker-entrypoint-initdb.d/secrets/postgres-passwd
  web_service:
    build: 
      context: .
      labels:
        "golang.go.goal=Run the main program an access to the database viewnext to get data"
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    networks: 
      - golang_postgreSQL
volumes:
  data: db/initDB.sql
  passwd: secrets/postgres-passwd